# Generated by Django 5.2.4 on 2025-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_text_comment_content_remove_bid_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watched_by", to="auctions.listing"
            ),
        ),
    ]
